-- Add is_uploaded_image column to track user-uploaded images vs AI-generated images
-- This allows conditional display of metadata overlays for full bleed cards

ALTER TABLE cards 
ADD COLUMN is_uploaded_image BOOLEAN DEFAULT false;

-- Add comment to document the column purpose
COMMENT ON COLUMN cards.is_uploaded_image IS 'Tracks whether the card image was uploaded by the user (true) or generated by AI (false). Used to conditionally hide metadata overlays on full bleed cards with uploaded images.';
